RFC initial design
iver-wharf/rfcs pull request #1
Opened 2021-04-19 17:12 UTC by jilleJr

Honest attemt at RFCs. This PR contains docs on how we think we should write RFCs, how we value them, and how we process them.

And not least, the template.

Please comment on the process, the template, or the docs themselves. Still, all of this can be changed after this has been merged, of course.

I've changed GitHub pages to point to this branch, so you can see it rendered here:

- Index page: <https://iver-wharf.github.io/rfcs/>
- Template: <https://iver-wharf.github.io/rfcs/0000-template> (it's unlisted)

2021-04-21 13:02 UTC, Pikabanga requested changes

2021-04-21 13:02 UTC, Pikabanga commented on 0000-template.md
> +Why do we need this? What's the problem you try to solve?
```suggestion
Why do we need this? What's the problem you are trying to solve?
```

2021-04-21 13:02 UTC, Pikabanga commented on 0000-template.md
> +backward compatability?
```suggestion
## Compatibility

Bring up compatibility issues and other things to regard. How will this interfere
with existing components (providers, database, frontend)? Does this break
backward compatibility?
```

2021-04-21 13:02 UTC, Pikabanga commented on README.md
> +Not every descision needs an RFC, nor is any RFC excessive. Altough this is the
```suggestion
Not every decision needs an RFC, nor is any RFC excessive. This is the
```

2021-04-21 13:02 UTC, Pikabanga commented on README.md
> +descision making. Only to have a place to look back at, similar to meeting
```suggestion
decision making. Only to have a place to look back at, similar to meeting
```

2021-04-21 13:02 UTC, Pikabanga commented on README.md
> +notes or recordings, so we can see our previous descisions.
```suggestion
notes or recordings, so we can see our previous decisions.
```

2021-04-21 13:02 UTC, Pikabanga commented on README.md
> +if you so want.
```suggestion
if you want.
```

2021-04-21 13:02 UTC, Pikabanga commented on _guides/rfc-life-cycle.md
> +3. **A descision is made.** Will the RFC be rejected, published, or postponed?
```suggestion
3. **A decision is made.** Will the RFC be rejected, published, or postponed?
```

2021-04-21 13:02 UTC, Pikabanga commented on _guides/what-needs-an-rfc.md
> +1. Brings backward incomptabile changes to the backend or the way you host
```suggestion
1. Brings backward incompatible changes to the backend or the way you host
```

2021-04-21 13:02 UTC, Pikabanga commented on index.md
> +Not every descision needs an RFC, nor is any RFC excessive. Altough this is the
```suggestion
Not every decision needs an RFC, nor is any RFC excessive. This is the
```

2021-04-21 13:02 UTC, Pikabanga commented on index.md
> +descision making. Only to have a place to look back at, similar to meeting
```suggestion
decision making. Only to have a place to look back at, similar to meeting
```

2021-04-21 13:02 UTC, Pikabanga commented on index.md
> +notes or recordings, so we can see our previous descisions.
```suggestion
notes or recordings, so we can see our previous decisions.
```

2021-04-21 14:02 UTC, jilleJr commented
If I got a nickel for every typo I made here...

Let's see here, 4 ~~compatability~~ compatibility, 7 ~~descision~~ decision... 0.55$! That's a FORTUNE!

2021-04-23 09:41 UTC, Pikabanga approved these changes
Great work!

I don't have any specific remarks. I think this is one of those things where we need to try it out and make adjustments over time.

2021-05-10 06:39 UTC, iverestefans approved these changes

2021-05-10 06:52 UTC, merged